version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - clickhouse
    restart: unless-stopped

  etl:
    build:
      context: .
      dockerfile: etl/Dockerfile
    container_name: etl
    working_dir: /app
    volumes:
      - ./etl:/app/etl
      - ./data:/app/data
      - ./database:/app/database
      - ./etl/logs:/app/etl/logs
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
    depends_on:
      - clickhouse
    restart: on-failure

volumes:
  clickhouse_data:
  metabase_data:
